var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,p="undefined"!=typeof WorkerGlobalScope,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ca=Object.assign({},f),da=[],ea="./this.program",fa=(a,b)=>{throw b;},r="",ha,ia;
if(ba){var fs=require("fs"),ja=require("path");r=__dirname+"/";ia=a=>{a=ka(a)?new URL(a):ja.normalize(a);return fs.readFileSync(a)};ha=a=>{a=ka(a)?new URL(a):ja.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(e,d)=>{e?c(e):b(d.buffer)})})};!f.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||p)p?r=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(r=document.currentScript.src),r=r.startsWith("blob:")?"":r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1),p&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=a=>ka(a)?new Promise((b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c(e.status)};e.onerror=c;e.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var la=f.print||console.log.bind(console),w=f.printErr||console.error.bind(console);Object.assign(f,ca);ca=null;f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);var ma=f.wasmBinary,na,x=!1,oa,y,z,pa,qa,E,ra,sa,ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}var I=0,za=null,Q=null;
function R(a){f.onAbort?.(a);a="Aborted("+a+")";w(a);x=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://"),Ba;function Ca(a){if(a==Ba&&ma)return new Uint8Array(ma);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}function Da(a){return ma?Promise.resolve().then(()=>Ca(a)):ha(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{w(`failed to asynchronously prepare wasm: ${e}`);R(e)})}function Fa(a,b){var c=Ba;ma||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||ka(c)||ba||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(d){w(`wasm streaming compile failed: ${d}`);w("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
var Ia={14520:()=>{window.H=[];window.addEventListener("message",function(a){if(a.data.constructor===Uint8Array)window.H.push(...a.data);else if(a.data.constructor===Array)switch(a.data[0]){case "putFile":window.localStorage[a.data[1]]=a.data[2];break;case "keyDown":window.keys.set(a.data[1],!0);break;case "keyUp":window.keys.set(a.data[1],!1);break;default:console.log("unrecognized message:",a.data[0])}},!1)},15042:()=>{var a=window.u?"session":"local";Object.keys(window.localStorage).forEach(function(b){window.parent.postMessage(["boardieGetFile",
b,window[a+"Storage"][b]],"*")})},15278:()=>window.H.splice(0,1)[0],15324:()=>{window.H||(window.H=[]);return 0<window.H.length},15417:(a,b,c)=>{for(var e=new Uint8Array(c-b),d=b;d<c;d++)e[d-b]=Ga(a+d);window.parent.postMessage(e,"*")},15571:()=>{window.keys=new Map;window.addEventListener("keydown",function(a){window.parent.postMessage(["boardieKeyDown",a.keyCode],"*");window.keys.set(a.keyCode,!0)},!1);window.addEventListener("keyup",function(a){window.parent.postMessage(["boardieKeyUp",a.keyCode],
"*");window.keys.set(a.keyCode,!1)},!1)},15937:()=>{window.B=new AudioContext;window.M=window.B.createGain();window.M.gain.value=.1;window.v=window.B.createOscillator();window.v.type="square";window.v.start();window.M.connect(window.B.destination)},16249:(a,b)=>{console.log(f.base64Encode(y.subarray(a,a+b),!0))},16327:()=>{var a=window.location.hash.indexOf("&files");0<a&&(window.u=!0,window.location.hash.substr(a+7).split(",").forEach(b=>{var c=b.indexOf(":"),e=decodeURIComponent(b.substring(0,c));
console.log("Loading",e);b=f.base64Decode(b.substring(c+1),!0);window.sessionStorage[e]=b}))},16823:a=>{if(window.location.hash.startsWith("#code=")){var b=window.location.hash.indexOf("&");b=window.location.hash.substring(6,-1<b?b:window.location.hash.length);console.log("Loading code from URL");if(b){b=f.base64Decode(b,!0);for(var c=0;c<b.length;c++){var e=a,d=b[c],g="i8";g.endsWith("*")&&(g="*");switch(g){case "i1":y[e]=d;break;case "i8":y[e]=d;break;case "i16":pa[e>>1]=d;break;case "i32":qa[e>>
2]=d;break;case "i64":R("to do setValue(i64) use WASM_BIGINT");case "float":ra[e>>2]=d;break;case "double":sa[e>>3]=d;break;case "*":E[e>>2]=d;break;default:R(`invalid type for setValue: ${g}`)}a++}}}},17208:()=>window.keys.get(37)||window.keys.get(65)||window.keys.get(84),17286:()=>window.keys.get(39)||window.keys.get(66)||window.keys.get(84),17364:()=>{window.v.U&&(window.v.disconnect(),window.v.U=!1,window.parent.postMessage(["boardieSoundStop"],"*"))},17524:a=>{window.v.frequency.value=a;window.v.U=
!0;window.parent.postMessage(["boardieSoundStart"],"*");window.v.connect(window.M)},17701:()=>{},17705:(a,b)=>{var c=0,e=new AudioBuffer({length:b,sampleRate:window.B.sampleRate}),d=e.getChannelData(0);for(let g=0;g<b;g++)d[g]=y[a+g]/255-.5,c++;window.D&&(window.D.stop(),window.D.disconnect());window.D=new AudioBufferSourceNode(window.B,{buffer:e});window.D.connect(window.B.destination);window.D.start();return c},18250:a=>{var b=window.K!=a;window.K=a;return b},18343:(a,b)=>{window.m.fillStyle="#000";
window.m.fillRect(0,0,a,b)},18413:(a,b)=>{window.L=document.createElement("canvas");window.L.width=a;window.L.height=b;window.m=window.L.getContext("2d",{alpha:!1});window.m.imageSmoothingEnabled=!1;(new FontFace("adafruit","url(adafruit_font.ttf)")).load().then(c=>{document.fonts.add(c)});window.s=function(c){return"rgb("+(c>>16&255)+","+(c>>8&255)+","+(c&255)+")"}},18949:()=>{window.N||(window.N=document.querySelector("#screen").getContext("2d",{alpha:!1}),window.N.imageSmoothingEnabled=!1);window.N.drawImage(window.L,
0,0)},19169:(a,b,c,e)=>{window.K||(window.K=65280);window.m.fillStyle=0==e?"#000":window.s(window.K);window.m.fillRect(a,b,c,c)},19360:()=>{var a=window.document.querySelector("#screen");window.S=0;window.T=0;window.C=!1;window.O=0;a.addEventListener("pointermove",function(b){window.S=Math.floor(b.clientX-a.offsetLeft);window.T=Math.floor(b.clientY-a.offsetTop)},!1);a.addEventListener("pointerdown",function(){window.C=!0;window.O=Date.now()},!1);a.addEventListener("pointerup",function(){window.C=
!1;window.O=0},!1)},19951:(a,b,c)=>{window.m.fillStyle=window.s(c);window.m.fillRect(a,b,1,1)},20036:(a,b,c)=>{window.m.fillStyle=window.s(c);window.m.fillRect(a,b,1,1)},20121:(a,b,c)=>{window.m.fillStyle=window.s(c);window.m.fillRect(a,b,1,1)},20206:(a,b,c)=>{window.m.fillStyle=window.s(c);window.m.fillRect(a,b,1,1)},20291:(a,b,c)=>{window.m.fillStyle=window.s(c);window.m.fillRect(a,b,1,1)},20376:(a,b,c,e,d)=>{window.m.strokeStyle=window.s(d);window.m.beginPath();window.m.moveTo(a,b);window.m.lineTo(c,
e);window.m.stroke()},20527:(a,b,c,e,d,g)=>{g?(window.m.fillStyle=window.s(d),window.m.fillRect(a,b,c,e)):(window.m.strokeStyle=window.s(d),window.m.strokeRect(a,b,c,e))},20722:(a,b,c,e,d,g,l)=>{l?window.m.fillStyle=window.s(g):window.m.strokeStyle=window.s(g);window.m.beginPath();window.m.moveTo(a+d,b);window.m.lineTo(a+c-d,b);window.m.arc(a+c-d,b+d,d,3*Math.PI/2,0,!1);window.m.lineTo(a+c,b+e-d);window.m.arc(a+c-d,b+e-d,d,0,Math.PI/2,!1);window.m.lineTo(a+d,b+e);window.m.arc(a+d,b+e-d,d,Math.PI/
2,Math.PI,!1);window.m.lineTo(a,b+d);window.m.arc(a+d,b+d,d,Math.PI,3*Math.PI/2,!1);l?window.m.fill():window.m.stroke()},21408:(a,b,c,e,d)=>{d?(window.m.fillStyle=window.s(e),window.m.beginPath(),window.m.arc(a,b,c,0,2*Math.PI),window.m.fill()):(window.m.strokeStyle=window.s(e),window.m.beginPath(),window.m.arc(a,b,c,0,2*Math.PI),window.m.stroke())},21750:(a,b,c,e,d,g,l,h)=>{h?window.m.fillStyle=window.s(l):window.m.strokeStyle=window.s(l);window.m.beginPath();window.m.moveTo(a,b);window.m.lineTo(c,
e);window.m.lineTo(d,g);window.m.closePath();h?window.m.fill():window.m.stroke()},22059:(a,b,c,e,d,g,l)=>{a=a?U(z,a):"";var h=b-d,n=c-d;0<=l&&(b=6*d*a.length,window.m.fillStyle=window.s(l),window.m.fillRect(h+d,n+d,b,8*d));var k=3==d?10.5*d:11*d;window.m.font=k+"px adafruit";window.m.fillStyle=window.s(e);window.m.textBaseline="top";a.split("").forEach(q=>{window.m.fillText(q,h,n);h+=6*d;g&&h+6*d>=window.m.canvas.width&&(h=0-d,n+=3*k/4)})},22748:(a,b,c,e,d,g,l,h)=>{var n=window.m.canvas.width/d;d=
window.m.canvas.height/d;c/=b;for(var k=0;k<c;k++)if(k+h<d&&0<=k+h)for(var q=0;q<b;q++)if(q+l<n&&0<=q+l){var t=z[a+k*b+q];t!==g&&(z[e+((h+k)*n+q+l)]=t)}},23206:(a,b)=>{window.P||(window.P=[]);window.P[b]=a},23281:(a,b,c,e,d,g)=>{b=b||1;var l=Math.ceil(window.m.canvas.width/b),h=Math.ceil(window.m.canvas.height/b);d=0<=d?d:l;g=0<=g?g:h;h=window.m.createImageData(d,g);var n=0,k=document.createElement("canvas");k.width=d;k.height=g;for(var q=e;q<e+g;q++)for(var t=c;t<c+d;t++){var ya=window.P[z[a+q*l+
t]];h.data[n]=ya>>16;h.data[n+1]=ya>>8&255;h.data[n+2]=ya&255;h.data[n+3]=255;n+=4}k.getContext("2d").putImageData(h,0,0);window.m.drawImage(k,c*b,e*b,d*b,g*b)},24291:()=>window.C,24319:()=>window.C?window.S:-1,24368:()=>window.C?window.T:-1,24417:()=>{if(window.C){var a=Date.now()-window.O;4095<a&&(a=4095)}else a=-1;return a},24607:a=>{window.A=new XMLHttpRequest;window.A.port=a;window.A.I=0},24721:()=>void 0!==window.A,24766:(a,b,c,e)=>{window.A=new XMLHttpRequest;var d=window.A;d.I=0;d.open(a?
U(z,a):"",window.location.protocol+"//"+(b?U(z,b):"")+"/"+(c?U(z,c):""));d.onreadystatechange=function(){4==d.readyState&&(d.R="HTTP/1.1 "+d.status+" "+d.statusText+"\r\n"+d.getAllResponseHeaders()+"\r\n\r\n"+d.responseText)};d.send(e?U(z,e):"")},25209:a=>{var b=window.A,c=0;b&&b.R&&(c=Math.min(b.R.length-b.I,799),V(b.R.substr(b.I,c),a,c+1),b.I+=c,0==c&&delete window.A);return c},25575:a=>window.keys.get(a),25607:a=>{a=a?U(z,a):"";"user-prefs"!==a&&(delete window[(window.u?"session":"local")+"Storage"][a],
delete window.o[a],window.parent.postMessage(["boardieDeleteFile",a],"*"))},25899:(a,b)=>{a=a?U(z,a):"";if("user-prefs"===a)return 0;var c=window.u?"session":"local";if(void 0===window[c+"Storage"][a])if(b)window[c+"Storage"][a]="";else return 0;window.J=5E4;window.o||(window.o={});if(!window.o[a]||b)window.o[a]=0;return 1},26366:a=>{a=a?U(z,a):"";return"user-prefs"===a?0:window.o[a]>=window[(window.u?"session":"local")+"Storage"][a].length},26595:(a,b)=>{a=a?U(z,a):"";if("user-prefs"!==a){var c=
window[(window.u?"session":"local")+"Storage"][a];if(window.o[a]<c.length){var e=c.indexOf("\n",window.o[a]);-1===e&&(e=c.length);V(c.substring(window.o[a],e),b,1024);window.o[a]=e+1}else V("",b,1024)}},27151:(a,b,c,e)=>{a=a?U(z,a):"";if("user-prefs"===a)return 0;var d=window[(window.u?"session":"local")+"Storage"][a];e=0<e?e:window.o[a];b=e+b>d.length?d.length:e+b;for(var g=e;g<b;g++)y[c]=d.charCodeAt(g),c++,(g-e)%window.J==window.J-1&&Ha(1);window.o[a]=b;return b-e},27735:(a,b,c)=>{a=a?U(z,a):"";
if("user-prefs"===a)return 0;var e=window[(window.u?"session":"local")+"Storage"][a],d=window.o[a];c=c+d>e.length?e.length:c+d;for(var g=d;g<c;g++)y[b]=e.charCodeAt(g),b++,(g-d)%window.J==window.J-1&&Ha(1);window.o[a]=c;return c-d},28303:a=>{a=a?U(z,a):"";return a in window.o?window.o[a]:0},28438:(a,b)=>{a=a?U(z,a):"";a in window.o&&(window.o[a]=b)},28600:(a,b)=>{a=a?U(z,a):"";if("user-prefs"!==a){b=b?U(z,b):"";var c=window.u?"session":"local";window[c+"Storage"][a]+=b+"\n";window.parent.postMessage(["boardieGetFile",
a,window[c+"Storage"][a]],"*")}},28923:(a,b,c)=>{var e=window.u?"session":"local";a=a?U(z,a):"";if("user-prefs"!==a){b=y.subarray(b,b+c);c=window[e+"Storage"][a];for(var d=0;d<b.length;d++)c+=String.fromCharCode(b[d]);window[e+"Storage"][a]=c;window.parent.postMessage(["boardieGetFile",a,window[e+"Storage"][a]],"*")}},29399:(a,b)=>{var c=window.u?"session":"local";a=a?U(z,a):"";"user-prefs"!==a&&(window[c+"Storage"][a]+=b?U(z,b):"",window.parent.postMessage(["boardieGetFile",a,window[c+"Storage"]],
"*"))},29688:a=>{var b=window.u?"session":"local";a=a?U(z,a):"";return"user-prefs"===a?0:window[b+"Storage"][a].length},29896:()=>{window.F=0},29929:a=>{var b=Object.keys(window[(window.u?"session":"local")+"Storage"]).filter(c=>"user-prefs"!==c);window.F||(window.F=0);window.F>=b.length?V("",a,100):(V(b[window.F],a,100),window.F++)},30325:a=>{"undefined"!==typeof navigator.requestMIDIAccess&&navigator.requestMIDIAccess().then(function(b){b=Array.from(b.outputs);var c=a;0<b.length&&(c=Math.min(c,
b.length-1),window.G=b[c][1],console.log("midi output:",window.G))})},30676:(a,b,c,e)=>{if("undefined"===typeof window.G)console.log("no midi output");else try{switch(a){case 1:window.G.send([b]);break;case 2:window.G.send([b,c]);break;case 3:window.G.send([b,c,e])}}catch(d){console.log(d)}}};class Ja{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ka=a=>{for(;0<a.length;)a.shift()(f)};
function Ga(a){var b="i8";b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a];case "i8":return y[a];case "i16":return pa[a>>1];case "i32":return qa[a>>2];case "i64":R("to do getValue(i64) use WASM_BIGINT");case "float":return ra[a>>2];case "double":return sa[a>>3];case "*":return E[a>>2];default:R(`invalid type for getValue: ${b}`)}}
var La=f.noExitRuntime||!0,Ma=[],Na=a=>{a instanceof Ja||"unwind"==a||fa(1,a)},Oa=a=>{oa=a;La||(f.onExit?.(a),x=!0);fa(a,new Ja(a))},Pa=a=>{oa=a;Oa(a)},Qa=()=>{if(!La)try{var a=oa;oa=a;Oa(a)}catch(b){Na(b)}},Ya=(a,b)=>{Ra=a;Sa=b;if(Ta)if(Ua||=!0,0==a)W=function(){setTimeout(X,Math.max(0,Va+b-performance.now())|0)};else if(1==a)W=function(){Wa(X)};else if(2==a){if("undefined"==typeof Xa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",e=>{if("setimmediate"===e.data||"setimmediate"===
e.data.target)e.stopPropagation(),c.shift()()},!0);Xa=e=>{c.push(e);if(p){let d;(d=f).setImmediates??(d.setImmediates=[]);f.setImmediates.push(e);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Xa=setImmediate;W=function(){Xa(X)}}},Ua=!1,W=null,Za=0,Ta=null,$a=0,Ra=0,Sa=0,ab=0,bb=[],cb=[],db=[],Y=0;
function Wa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Y)Y=b+1E3/60;else for(;b+2>=Y;)Y+=1E3/60;setTimeout(a,Math.max(Y-b,0))}}
var eb={},Va,X,Xa,fb,gb=(a,b,c,e,d)=>{function g(){return l<Za?(Qa(),!1):!0}Ta=a;$a=e;var l=Za;Ua=!1;X=function(){if(!x)if(0<bb.length){var h=bb.shift();h.Y(h.V);if(fb){var n=fb,k=0==n%1?n-1:Math.floor(n);fb=h.W?k:(8*n+(k+.5))/9}f.setStatus&&(h=f.statusMessage||"Please wait...",n=fb??0,k=eb.X??0,n?n<k?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(h):f.setStatus(""));g()&&setTimeout(X,0)}else if(g())if(ab=ab+1|0,1==Ra&&1<Sa&&0!=ab%Sa)W();else{0==Ra&&(Va=performance.now());
a:if(!x){for(h of cb)if(!1===h())break a;if(!x)try{a(),Qa()}catch(q){Na(q)}for(n of db)n()}g()&&W()}};d||(b&&0<b?Ya(0,1E3/b):Ya(1,1),W());if(c)throw"unwind";},hb=[],ib,jb=[null,[],[]],kb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,U=(a,b=0)=>{for(var c=b+NaN,e=b;a[e]&&!(e>=c);)++e;if(16<e-b&&a.buffer&&kb)return kb.decode(a.subarray(b,e));for(c="";b<e;){var d=a[b++];if(d&128){var g=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|g);else{var l=a[b++]&63;d=224==(d&240)?(d&15)<<
12|g<<6|l:(d&7)<<18|g<<12|l<<6|a[b++]&63;65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}return c},V=(a,b,c)=>{var e=z;if(0<c){c=b+c-1;for(var d=0;d<a.length;++d){var g=a.charCodeAt(d);if(55296<=g&&57343>=g){var l=a.charCodeAt(++d);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=
240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}};f.requestAnimationFrame=Wa;f.pauseMainLoop=function(){W=null;Za++};f.resumeMainLoop=function(){Za++;var a=Ra,b=Sa,c=Ta;Ta=null;gb(c,0,!1,$a,!0);Ya(a,b);W()};f.preMainLoop&&cb.push(f.preMainLoop);f.postMainLoop&&db.push(f.postMainLoop);
var lb={d:(a,b,c)=>z.copyWithin(a,b,b+c),a:(a,b,c)=>{Ma.length=0;for(var e;e=z[b++];){var d=105!=e;d&=112!=e;c+=d&&c%8?4:0;Ma.push(112==e?E[c>>2]:105==e?qa[c>>2]:sa[c>>3]);c+=d?8:4}return Ia[a](...Ma)},c:()=>Date.now(),e:(a,b,c)=>{var e=hb[a];e||(a>=hb.length&&(hb.length=a+1),hb[a]=e=ib.get(a));gb(e,b,c)},b:(a,b,c,e)=>{for(var d=0,g=0;g<c;g++){var l=E[b>>2],h=E[b+4>>2];b+=8;for(var n=0;n<h;n++){var k=z[l+n],q=jb[a];0===k||10===k?((1===a?la:w)(U(q)),q.length=0):q.push(k)}d+=h}E[e>>2]=d;return 0}},
Z=function(){function a(c){Z=c.exports;na=Z.f;c=na.buffer;f.HEAP8=y=new Int8Array(c);f.HEAP16=pa=new Int16Array(c);f.HEAPU8=z=new Uint8Array(c);f.HEAPU16=new Uint16Array(c);f.HEAP32=qa=new Int32Array(c);f.HEAPU32=E=new Uint32Array(c);f.HEAPF32=ra=new Float32Array(c);f.HEAPF64=sa=new Float64Array(c);ib=Z.j;ua.unshift(Z.g);I--;f.monitorRunDependencies?.(I);0==I&&(null!==za&&(clearInterval(za),za=null),Q&&(c=Q,Q=null,c()));return Z}I++;f.monitorRunDependencies?.(I);var b={a:lb};if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){return w(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ba??=Aa("run_boardie.wasm")?"run_boardie.wasm":f.locateFile?f.locateFile("run_boardie.wasm",r):r+"run_boardie.wasm";Fa(b,function(c){a(c.instance)});return{}}();f._getScripts=()=>(f._getScripts=Z.h)();var mb=f._main=(a,b)=>(mb=f._main=Z.i)(a,b),Ha=f._taskSleep=a=>(Ha=f._taskSleep=Z.k)(a),nb=a=>(nb=Z.l)(a),ob;Q=function pb(){ob||qb();ob||(Q=pb)};
function rb(a=[]){var b=mb;a.unshift(ea);var c=a.length,e=nb(4*(c+1)),d=e;a.forEach(l=>{for(var h=E,n=d>>2,k=0,q=0;q<l.length;++q){var t=l.charCodeAt(q);127>=t?k++:2047>=t?k+=2:55296<=t&&57343>=t?(k+=4,++q):k+=3}k+=1;q=nb(k);V(l,q,k);h[n]=q;d+=4});E[d>>2]=0;try{var g=b(c,e);Pa(g)}catch(l){Na(l)}}
function qb(){var a=da;function b(){if(!ob&&(ob=!0,f.calledRun=!0,!x)){Ka(ua);Ka(va);f.onRuntimeInitialized?.();sb&&rb(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.unshift(c)}Ka(wa)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Ka(ta);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var sb=!0;f.noInitialRun&&(sb=!1);qb();
